services:
  # MySQL
  # compose 테스트
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # bbatty 서비스
  bbatty-service:
    build:
      context: ./bbatty
      dockerfile: Dockerfile
    container_name: bbatty-service
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}

      JWT_SECRET: ${JWT_SECRET}

      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

  # 채팅 서비스 인스턴스 1
  chat-service-1:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: chat-service-1
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      chat-redis:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_DATA_REDIS_HOST: chat-redis
      SPRING_DATA_REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      command : redis-server --requirepass ${REDIS_PASSWORD}
      
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: bbatty-chat

      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      
      # 인스턴스 구분용 ID
      CHAT_INSTANCE_ID: "chat-instance-1"

  # 채팅 서비스 인스턴스 2
  chat-service-2:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: chat-service-2
    ports:
      - "8085:8084"
    depends_on:
      mysql:
        condition: service_healthy
      chat-redis:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_DATA_REDIS_HOST: chat-redis
      SPRING_DATA_REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      command : redis-server --requirepass ${REDIS_PASSWORD}
      
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: bbatty-chat

      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      
      # 인스턴스 구분용 ID
      CHAT_INSTANCE_ID: "chat-instance-2"

  # Nginx 로드밸런서
  nginx-chat-lb:
    image: nginx:alpine
    container_name: nginx-chat-lb
    ports:
      - "8083:80"  # 외부 8083 포트로 로드밸런서 접근
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-service-1
      - chat-service-2
    networks:
      - app-network
    restart: unless-stopped

  # 스케줄 서비스
  schedule-service:
    build:
      context: ./schedule
      dockerfile: Dockerfile
    container_name: schedule-service
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      OPENAI_GPT_KEY: ${OPENAI_GPT_KEY}

      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}

      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}

      JWT_SECRET: ${JWT_SECRET}

      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

  # Redis 캐시
  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # 새로운 Redis (chat용)
  chat-redis:
    image: redis:alpine
    container_name: redis-chat
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - chat_redis_data:/data
    networks:
      - app-network

  # Kafka (KRaft mode - no Zookeeper needed)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_METADATA_MAX_AGE_MS: 60000          # 1분 (기본 5분 → 1분)

    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app-network

volumes:
  mysql_data:
  jenkins_data:
  redis_data:
  chat_redis_data:
  kafka_data:

networks:
  app-network:
    driver: bridge
