# BBATTY 애플리케이션 설정 파일 (기존 properties 대체)
spring:
  application:
    name: bbatty

  # 데이터베이스 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Redis 설정
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: bbatty-auth-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# AWS S3 설정
cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

# WebSocket 설정
websocket:
  allowed-origins: "*"
  sockjs:
    enabled: false

# WebSocket - Chatting 설정
chat:
  game:
    enable-spam-filter: false
    enable-profanity-filter: false
  match:
    auto-create-room: true

# Kakao OAuth 설정
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  user-info-url: https://kapi.kakao.com/v2/user/me
  redirect-uri: ${KAKAO_REDIRECT_URI}
  timeout-seconds: 10
  scope: account_email,birthday,gender

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  issuer: bbatty
  header: Authorization
  prefix: Bearer
  access-token-validity-hours: 1
  refresh-token-validity-days: 30
  refresh-threshold-minutes: 10

# Firebase 설정
firebase:
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH}
  project-id: ${FIREBASE_PROJECT_ID}

logging:
  level:
    root: INFO
    com.ssafy: DEBUG
    com.google.firebase: DEBUG