import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e5e5e7',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#f2f2f7',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#d1d1d6',
    paddingHorizontal: 16,
    paddingVertical: 10,
    minHeight: 44,
  },
  input: {
    flex: 1,
    fontSize: 16,
    lineHeight: 20,
    color: '#000000',
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 0,
    minHeight: 40,
    maxHeight: 80,
    textAlignVertical: 'top',
    includeFontPadding: false,
  },
  inputError: {
    borderColor: '#ff3b30',
    backgroundColor: '#fff5f5',
  },
  actions: {
    marginLeft: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  characterCount: {
    fontSize: 11,
    color: '#8e8e93',
    marginBottom: 4,
    minWidth: 40,
    textAlign: 'center',
  },
  sendButton: {
    backgroundColor: '#007aff',
    borderRadius: 16,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#007aff',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  sendButtonDisabled: {
    backgroundColor: '#c7c7cc',
    shadowOpacity: 0,
    elevation: 0,
  },
  sendButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  sendButtonTextDisabled: {
    color: '#8e8e93',
  },
  errorContainer: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#fff2f2',
    borderRadius: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#ff3b30',
  },
  errorText: {
    color: '#ff3b30',
    fontSize: 13,
    lineHeight: 18,
  },
});